# Tokyo Night tokyonight-storm theme for Hyprland

general {
    col.active_border = rgba(#7aa2f7) rgba() 45deg
    col.inactive_border = rgba(#363a4faa)
}

decoration {
    shadow {
        color = rgba(#24283baa)
    }
}
