# Tokyo Night tokyonight-day theme for Hyprland

general {
    col.active_border = rgba(#3760bf) rgba() 45deg
    col.inactive_border = rgba(#dcdfe4aa)
}

decoration {
    shadow {
        color = rgba(#e6e7edaa)
    }
}
