# Tokyo Night tokyonight-day theme for Kitty

# Basic colors
foreground              #3760bf
background              #e1e2e7
selection_foreground    #e1e2e7
selection_background    #3760bf

# Cursor colors
cursor                  #3760bf
cursor_text_color       #e1e2e7

# URL underline color
url_color               #387068

# Window border colors
active_border_color     #2e7de9
inactive_border_color   #c4c8da
bell_border_color       #f52a65

# Tab bar colors
active_tab_foreground   #d0d5e3
active_tab_background   #2e7de9
inactive_tab_foreground #8990b3
inactive_tab_background #c4c8da
#tab_bar_background      #b4b5b9

# Colors for marks
mark1_foreground        #e1e2e7
mark1_background        #2e7de9
mark2_foreground        #e1e2e7
mark2_background        #9854f1
mark3_foreground        #e1e2e7
mark3_background        #25a45c

# Black
color0                  #b4b5b9
color8                  #a1a6c5

# Red
color1                  #f52a65
color9                  #ff4774

# Green
color2                  #587539
color10                 #5c8524

# Yellow
color3                  #8c6c3e
color11                 #a27629

# Blue
color4                  #2e7de9
color12                 #358aff

# Magenta
color5                  #9854f1
color13                 #a463ff

# Cyan
color6                  #007197
color14                 #007ea8

# White
color7                  #6172b0
color15                 #3760bf
