# Apparatus Hyprpaper Configuration
# https://wiki.hypr.land/Hypr-Ecosystem/hyprpaper/

# Fallback wallpaper for all monitors
wallpaper {
    monitor = *
    path = /usr/share/apparatus/wallpapers/default.jpg
    fit_mode = cover
}

# Disable splash
splash = false

# Enable IPC
ipc = on
