# Tokyo Night tokyonight-night theme for Hyprland

general {
    col.active_border = rgba(#7aa2f7) rgba() 45deg
    col.inactive_border = rgba(#24283baa)
}

decoration {
    shadow {
        color = rgba(#1a1b26aa)
    }
}
