# Tokyo Night tokyonight-moon theme for Kitty

# Basic colors
foreground              #c8d3f5
background              #222436
selection_foreground    #222436
selection_background    #2d3f76

# Cursor colors
cursor                  #c8d3f5
cursor_text_color       #222436

# URL underline color
url_color               #4fd6be

# Window border colors
active_border_color     #82aaff
inactive_border_color   #2f334d
bell_border_color       #ff757f

# Tab bar colors
active_tab_foreground   #1e2030
active_tab_background   #82aaff
inactive_tab_foreground #545c7e
inactive_tab_background #2f334d
#tab_bar_background      #1b1d2b

# Colors for marks
mark1_foreground        #222436
mark1_background        #7aa2f7
mark2_foreground        #222436
mark2_background        #bb9af7
mark3_foreground        #222436
mark3_background        #9ece6a

# Black
color0                  #1b1d2b
color8                  #444a73

# Red
color1                  #ff757f
color9                  #ff8d94

# Green
color2                  #c3e88d
color10                 #c7fb6d

# Yellow
color3                  #ffc777
color11                 #ffd8ab

# Blue
color4                  #82aaff
color12                 #9ab8ff

# Magenta
color5                  #c099ff
color13                 #caabff

# Cyan
color6                  #86e1fc
color14                 #b2ebff

# White
color7                  #828bb8
color15                 #c8d3f5
